version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sanad_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sanad
      POSTGRES_PASSWORD: sanad_dev
      POSTGRES_DB: sanad
    ports:
      - "5432:5432"
    volumes:
      - sanad_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sanad"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sanad_pgdata:
